spring.application.name=backend
server.port = 8082

spring.datasource.url=jdbc:postgresql://localhost:5432/tms_project_db
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

app.jwt.secret = F2A1D9C8B7E6A5D4C3B2A19087654321F1E2D3C4B5A6978877665544332211FFE
app.jwt.issuer = shamnasecurity
app.jwt.expiration = 7200000